title: Omid Ghadami
theme: jekyll-theme-minimal
description: Software Engineer
logo: https://media.licdn.com/dms/image/C5603AQFceUcAQk_gKw/profile-displayphoto-shrink_400_400/0/1643929555043?e=1715212800&v=beta&t=tw3J_yHPa2Wu-_OBKkYeNVHPC7zzrIdb6stwfpBVdec
show_downloads: true
